server:
  port: 8761

spring:
  application:
    name: admin
  boot:
    admin:
      context-path: /monitor
  security:
    user:
      name: ${USER_NAME:admin}
      password: ${USER_PASSWORD:asdf}
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}