server:
  port: 8888
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: config
  jmx:
    enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/now-start/config-service
          search-paths: src/main/resources/config/*
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:localhost:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

encrypt:
  key: ${ENCRYPT_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  charset:
    file: UTF-8
  file:
    path: ./logs
  logback:
    rollingpolicy:
      max-history: 7
  level:
    com.netflix : warn
    org.springframework.cloud.config : warn