server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/now-start/config-service
          search-paths: src/main/resources/properties/*
          default-label: main



eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

