server:
  port: 8888
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/now-start/config-service
          search-paths: src/main/resources/config/*

encrypt:
  key: ${ENCRYPT_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  file:
    path: ./logs
  charset:
    file: UTF-8