server:
  port: 8888
  shutdown: graceful

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties


eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

