server:
  port: 8888
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/now-start/config-service
          search-paths: src/main/resources/config/*
        encrypt:
          enabled: false

eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
  client:
    service-url:
      defaultZone: ${SERVICE_URL:}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  file:
    path: ./logs
  charset:
    file: UTF-8